services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_net

networks:
  todo_net:
    driver: bridge

volumes:
  mysql_data: